import * as Shape from "@/components";

export const addModules = [
  {
    icon: <Shape.Shape1 />,
    title: "CRM-Enrol & Forms",
    desc: "Want to make your admissions process easier? Check out Classe365's CRM-Enrol & Forms module! It helps you streamline enrollment, and create custom forms all in one place.",
    price: "$50/Month",
    priceDesc: "(For every 1500 submission)",
    bullets: [
      "Keep track of potential student recruits and enrollments with just a couple of clicks",
      "Streamline the student enrolling process with our super-convenient one-click enrollment option",
      "Effortlessly create and manage generic forms with advanced workflows",
    ],
  },
  {
    icon: <Shape.Shape5 />,
    title: "Learning Management System",
    desc: "Transform your school with Classe365's easy-to-use Learning Management System. Plan lessons, administer coursework, and improve results with our advanced and effortless platform.",
    price: "$50/Month",
    priceDesc: "(For every 1500 submission)",
    bullets: [
      "Plan your lessons without any hassle",
      "Streamline curriculum mapping and tracking and make things easier and more efficient",
      "Engage students with pre-class resources and interactive in-class discussions with our Flipped Class feature",
      "Create and manage interactive and fun quizzes efficiently",
    ],
  },
  {
    icon: <Shape.Shape8 />,
    title: "Fee & Invoicing",
    desc: "With Classe365's Fee & Invoicing feature, you can generate invoices, give parents the option to pay online, and make sure financial transactions go off without a hitch.",
    price: "$50/Month",
    priceDesc: "(For every 1500 submission)",
    bullets: [
      "Simplify your fee management with Classe365's seamless invoice management system",
      "Accept fee payments quickly and easily through our easy-to-use web and mobile app",
      "Easily connect with well-known payment gateways to safely handle online payments",
    ],
  },
  {
    icon: <Shape.Shape9 />,
    title: "Financial Accounting",
    desc: "Are you ready to take control of your school's finances? Classe365 enables you to keep your books in order, generate statements, reconcile transactions, and stay on top of your finances!",
    price: "$50/Month",
    priceDesc: "(For every 1500 submission)",
    bullets: [
      "Take the hassle out of managing your finances with Classe365's easy-to-use accounting software",
      "Keep tabs on your income and expenses by generating precise Profit and Loss statements",
      "Monitor your assets, debts, and net worth with balance sheets",
      "Keep track of your financial transactions with detailed and well-organised ledger statements",
      "Reconcile your financial records easier by comparing and double-checking the transactions",
    ],
  },
  {
    icon: <Shape.Shape7 />,
    title: "Alumni",
    desc: "With Classe365's Alumni module, you can reach out to former students, manage an organised directory of alumni, and create lasting connections for networking and long-term support.",
    price: "$50/Month",
    priceDesc: "(For every 1500 submission)",
    bullets: [
      "Classe365 enables you to keep your alumni in the loop about all the exciting stuff going on at school",
      "Our comprehensive alumni directory makes it easy to search for former students and build a thriving alumni community",
      "Seamlessly change your student's status from “Student” to “Alumni” and vice versa",
    ],
  },
  {
    icon: <Shape.Shape6 />,
    title: "E-Commerce Store",
    desc: "Unlock a world of opportunities for your school with Classe365's ECommerce Store! Sell products and courses, track inventory, and give students and parents a smooth shopping experience.",
    price: "$50/Month",
    priceDesc: "(For every 1500 submission)",
    bullets: [
      "Set up your private online store and offer exclusive products and courses to your school's community",
      "Keep your products organised and sorted into categories to make shopping easier",
      "Keep tabs on orders, monitor inventory, and make sure purchases are delivered in a timely manner",
      "Who doesn't love a good discount? Classe365 enables you to give your customers discounts and promotions to increase sales",
    ],
  },
  {
    icon: <Shape.Shape10 />,
    title: "White label",
    desc: "Make Classe365 uniquely yours with our White Label Module! Personalise the platform with your own logo, domain, and styling to deliver a consistent experience for everyone.",
    price: "$50/Month",
    priceDesc: "(For every 1500 submission)",
    bullets: [
      "Make your domain and URLs stand out by personalising them to fit your school's unique image",
      "Get rid of those branding distractions – get a smooth user experience by hiding Classe365's branding elements",
      "Make the most of the customization options to give your platform a fresh look and feel",
    ],
  },
  {
    icon: <Shape.Shape11 />,
    title: "Fund Raising",
    desc: "Make fundraising easy with Classe365! Our platform is your one-stop shop for all of your fundraising and donor management requirements.",
    price: "$50/Month",
    priceDesc: "(For every 1500 submission)",
    bullets: [
      "Make custom forms to collect your donations, sponsorships, and pledges - perfect for your special fund-raising activities",
      "Manage donor relationships without all-inclusive CRM. Keep tabs on donor info and interactions with ease",
      "Classe365 integrates with your CRM and reliable payment gateways for a smooth and protected donation process",
    ],
  },
  {
    icon: <Shape.Shape12 />,
    title: "Degree Audit",
    desc: "Track your students' academic progress and give them the support they need to finish their degree with Classe365's Degree Audit! Track their progress and give students a boost on their path to graduation.",
    price: "$50/Month",
    priceDesc: "(For every 1500 submission)",
    bullets: [
      "With Classe365's Degree Audit, you can quickly create custom course plans and follow your student's progress",
      "Keep track of your student's progress to make sure they stay on track and get their degree in a timely manner",
    ],
  },
  {
    icon: <Shape.Shape13 />,
    title: "Education Agent Module",
    desc: "Easily build and keep up with your network of education agents using Classe365's Education Agent Module! It's a great way to stay connected and manage your network.",
    price: "$50/Month",
    priceDesc: "(For every 1500 submission)",
    bullets: [
      "Keep up with your agent's commissions hassle-free and precisely, making sure the financial transactions are crystal clear",
      "Make communication smoother by keeping education agents in the loop and providing them with help, updates, and collaboration opportunities",
      "Create a comprehensive education agent database to scale your student recruitment channel. Explore new avenues and reach a wider pool of potential students",
    ],
  },
  {
    icon: <Shape.Shape14 />,
    title: "Enterprise Pro Plan",
    desc: "Classe365's Enterprise Pro Plan gives you access to pro-level features, increased storage space, customisations, and more to help your school reach its full potential.",
    price: "$50/Month",
    priceDesc: "(For every 1500 submission)",
    bullets: [
      "Enjoy increased storage space on your LMS with LMS Pro. Never worry about running out of space again!",
      "Unlock advanced access to our secure API for smoother integration with other systems",
      "Customise and give Classe365 a personal touch with our White-label Pro feature",
      "Looking for a unique way to engage with students, parents, and staff? Make the most of our Private Label Mobile App",
      "Enjoy Private Cloud options like AWS, Azure, or Google Compute Engine",
      "Unlock powerful insights with Power BI and Google Data Studio",
      "Easily integrate Classe365 with popular ERP systems such as Salesforce, SAP, and Oracle Fusion",
    ],
  },
];
